version: "3"

services:
  server:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
  mysqldb:
   platform: linux/x86_64
   image: "mysql:8.0"
   restart: always
   ports:
     - 3306:3306
   environment:
     MYSQL_DATABASE: book_a_car
     MYSQL_USER: root
     MYSQL_PASSWORD: 123
     MYSQL_ROOT_PASSWORD: 123